services:
  postgres:
    restart: unless-stopped
    image: postgres:14
    hostname: postgres
    volumes:
      - semaphore-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: semaphore
      POSTGRES_PASSWORD: semaphorepassword
      POSTGRES_DB: semaphore
  semaphore:
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    user: "${UID}:${GID}" ## create new user and group and add those UID and GID.
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphorepassword
      SEMAPHORE_DB_HOST: postgres
      SEMAPHORE_DB_PORT: 5432
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore
      SEMAPHORE_ADMIN_PASSWORD: password123
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@local
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: L8JS/duN93usMpMt0O5N9UHLGWosQR3fiZ2zukx4gpk= 
      SEMAPHORE_LDAP_ACTIVATED: 'no'
      TZ: UTC+1
    depends_on:
      - postgres
volumes:
  semaphore-postgres:
